name: payausers
description: A new Flutter secret project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Have Responsive size in any Devices
  sizer: ^1.1.8
  cupertino_icons: ^1.0.0
  hexcolor: ^1.0.6
  # MarkDown Plug in
  flutter_markdown:
  carousel_slider: ^2.3.1
  dio: 
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  file_picker:
  path_provider:
  image_picker: ^0.7.4
  image_native_resizer: ^0.1.2
  flutter_datetime_picker: ^1.5.0
  list_tile_switch: ^0.0.2
  toast: ^0.1.5
  # Does not work flutter secure storage
  # flutter_secure_storage: ^3.3.5
  persian_number_utility: ^0.2.5
  lottie:
  qr_flutter: ^3.1.0
  persian_datepicker: ^1.3.1
  rflutter_alert: ^1.1.0
  double_back_to_close_app: 
  modal_bottom_sheet: ^1.0.0+1
  liquid_pull_to_refresh: ^1.2.0
  flutter_slidable:
  ticketview: ^1.0.0
  flushbar: ^1.10.4
  adaptive_action_sheet: ^1.0.11
  connectivity: ^2.0.2
  # Converted Image
  image_picker_web: ^2.0.1
  image: 
  numberpicker: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: BYekan
      fonts:
        - asset: assets/fonts/byekan/BYEKAN.TTF

    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
